### PR TITLE
Add `xml` command

### LINKED ISSUE #192: Serialize PICA+ to XML
see https://format.gbv.de/pica/xml

### PR DESCRIPTION
**Pull request by niko2342**
This change adds a new command to serialize PICA+ records to [PICA XML](https://verbundwiki.gbv.de/display/VZG/PICA+XML+Version+1.0).

The command 
```shell
$ pica xml --skip-invalid tests/data/1004916019.dat
```

produces the following XMl document:

```xml
<?xml version="1.0" encoding="utf-8"?>
<collection xmlns="info:srw/schema/5/picaXML-v1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="info:srw/schema/5/picaXML-v1.0">
  <record>
    <datafield tag="001A">
      <subfield code="0">8999:22-07-10</subfield>
    </datafield>
    <datafield tag="001B">
      <subfield code="0">1250:10-09-14</subfield>
      <subfield code="t">08:28:16.000</subfield>
    </datafield>
    <datafield tag="001D">
      <subfield code="0">0384:27-07-10</subfield>
    </datafield>
    <datafield tag="001U">
      <subfield code="0">utf8</subfield>
    </datafield>
    <datafield tag="001X">
      <subfield code="0">0</subfield>
    </datafield>
    <datafield tag="002@">
      <subfield code="0">Ts1</subfield>
    </datafield>
    <datafield tag="003@">
      <subfield code="0">1004916019</subfield>
    </datafield>
    <datafield tag="003U">
      <subfield code="a">http://d-nb.info/gnd/7710287-3</subfield>
    </datafield>
    <datafield tag="004B">
      <subfield code="a">sip</subfield>
    </datafield>
    <datafield tag="007K">
      <subfield code="a">gnd</subfield>
      <subfield code="0">7710287-3</subfield>
    </datafield>
    <datafield tag="007N">
      <subfield code="a">swd</subfield>
      <subfield code="0">7710287-3</subfield>
      <subfield code="v">zg</subfield>
    </datafield>
    <datafield tag="008A">
      <subfield code="a">s</subfield>
    </datafield>
    <datafield tag="029R">
      <subfield code="9">952570254</subfield>
      <subfield code="7">Tb1</subfield>
      <subfield code="V">kiz</subfield>
      <subfield code="A">gnd</subfield>
      <subfield code="0">5263070-5</subfield>
      <subfield code="a">Chrysler Corporation</subfield>
      <subfield code="4">hers</subfield>
    </datafield>
    <datafield tag="041A">
      <subfield code="a">Plymouth</subfield>
      <subfield code="g">Marke</subfield>
    </datafield>
    <datafield tag="041R">
      <subfield code="9">041145135</subfield>
      <subfield code="7">Ts1</subfield>
      <subfield code="V">saz</subfield>
      <subfield code="A">gnd</subfield>
      <subfield code="0">4114513-6</subfield>
      <subfield code="a">Markenname</subfield>
      <subfield code="4">obin</subfield>
    </datafield>
    <datafield tag="042A">
      <subfield code="a">31.7</subfield>
    </datafield>
    <datafield tag="047A">
      <subfield code="e">DE-210</subfield>
    </datafield>
    <datafield tag="047A">
      <subfield code="r">DE-384</subfield>
    </datafield>
    <datafield tag="047C">
      <subfield code="S">swd</subfield>
      <subfield code="i">s</subfield>
      <subfield code="a">Plymouth &lt;Marke></subfield>
      <subfield code="0">7710287-3</subfield>
    </datafield>
    <datafield tag="050D">
      <subfield code="a">Kombiniere mit einer Produktgruppe, z.B. Personenkraftwagen</subfield>
    </datafield>
    <datafield tag="050E">
      <subfield code="a">Wikipedia, Internet</subfield>
      <subfield code="u">http://www.mobile.de/modellverzeichnis/plymouth/</subfield>
    </datafield>
    <datafield tag="050H">
      <subfield code="a">Markenname</subfield>
    </datafield>
  </record>
</collection>
```

Closes #192

### CODE REVIEW

**Comment by niko2342** [comment]
@nichtich  Can you take a short review of the new `xml` command? Is the XML format was implemented correctly?

Record: [1004916019.dat](https://github.com/deutsche-nationalbibliothek/pica-rs/blob/main/tests/data/1004916019.dat), Serizalization: [1004916019.dat](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/359/files#diff-03460f9760f1ccd9df9f2e4b07c33dc47495c6827257976fd5daaadc253cbfaa)

**Comment by nichtich** [comment]
Why a command instead of an option? `picadata` used `--from` and `--to` to specify serialization format (see #274). I recomment to add `--to`, use `--to xml` for serializing `xml` and to make `--to plain` an alias for command `print`. Benefit: it becomes possible to `filter` or `sample` and emit resulting records in selected serialization.

**Comment by niko2342** [comment]
It was a design decision to work on PICA+, because this is the most efficient PICA "dialect" regarding data analysis on large datasets. The "exit"-commands (json, xml or select) are used for downstream tools/libraries like Python/Pandas, R or picadata.

I can understand that supporting more pica dialects could be a very useful (filter syntax), but I need more time to think about the implications for the software architecture. At this time, only PICA+ is supported as input dialect.

**Comment by nichtich** [comment]
> @nichtich Can you take a short review of the new `xml` command? Is the XML format implemented correctly?

Sorry, I did not have the time yet. The writer omits the `occurrence` attribute, e.g. `012X/01 $aBC` in PICA XML should be:

~~~xml
<datafield tag="012X" occurrence="01">
      <subfield code="a">BC</subfield>
</datafield>
~~~

**Comment by niko2342** [comment]
@nichtich Thanks a lot! I completely forgot the `occurrence` attribute.

**Pull request merged**
